###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark

server:
  address: tcp://0.0.0.0:9091
  buffers:
    read: 4096
    write: 4096
  # enable_pprof: false
  # enable_expvars: false
  # disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
log:
  level: debug

totp:
  issuer: auth.thehorde.page
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: 
        - "*.thehorde.page"
      policy: bypass 
      resources:
        - "^/api([/?].*)?$"
        - "^/identity.*$"
        - "^/triggers.*$"
        - "^/meshagents.*$"
        - "^/meshsettings.*$"
        - "^/agent.*$"
        - "^/control.*$"
        - "^/meshrelay.*$"
        - "^/wl.*$"
    - domain: 
        - "auth.thehorde.page"
      policy: bypass 
    - domain: "home.thehorde.page"
      policy: one_factor        
    - domain: "proxy.thehorde.page" 
      policy: two_factor
    - domain: "uptime.thehorde.page" 
      policy: two_factor          
    - domain: "net.thehorde.page" 
      policy: two_factor      
    - domain: "proxmox.thehorde.page" 
      policy: two_factor 
    - domain: "nas.thehorde.page"
      policy: two_factor  
    - domain: "prowlarr.thehorde.page" 
      policy: one_factor  
    - domain: "bazarr.thehorde.page" 
      policy: one_factor
    - domain: "torrent.thehorde.page" 
      policy: one_factor                 
    - domain: "sonarr.thehorde.page" 
      policy: one_factor
    - domain: "radarr.thehorde.page" 
      policy: one_factor
    - domain: "lidarr.thehorde.page" 
      policy: one_factor      
    - domain: "calibre.thehorde.page" 
      policy: one_factor
    - domain: "podcast.thehorde.page" 
      policy: one_factor  
    - domain: "models.thehorde.page" 
      policy: one_factor
    - domain: "photos.thehorde.page" 
      policy: two_factor
    - domain: "vehicles.thehorde.page" 
      policy: one_factor            
  
session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  remember_me:  24h
  cookies:
    - domain: thehorde.page
      authelia_url: 'https://auth.thehorde.page'
      default_redirection_url: 'https://www.thehorde.page'

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /db/db.sqlite3
  
notifier:
  disable_startup_check: true
  smtp:
    address: smtp.gmail.com:587
    username: thehorde.mail@gmail.com
    sender: thehorde.mail@gmail.com
    identifier: thehorde
    subject: "[Authelia] {title}"
    startup_check_address: thehorde.mail@gmail.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2