networks:
  cloudflared:
    name: cloudflared
services:

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: True
      WATCHTOWER_INCLUDE_STOPPED: True
      WATCHTOWER_NOTIFICATIONS: gotify
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: Server
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: /run/secrets/gotify_token
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: http://42.42.20.2:4624
      WATCHTOWER_REVIVE_STOPPED: False
      WATCHTOWER_SCHEDULE: 0 00 05 * * 0
    networks:
      - cloudflared
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secrets/watchtower/gotify_token:/run/secrets/gotify_token:ro


  cloudflared:
    command: tunnel --no-autoupdate run
    container_name: cloudflared
    image: cloudflare/cloudflared
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/tunnel_token
      TZ: Europe/Zurich
    networks:
      - cloudflared
    restart: unless-stopped
    volumes:
      - ./secrets/cloudflared/tunnel_token:/run/secrets/tunnel_token:ro

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    networks:
      - cloudflared
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./appdata/traefik/acme.json:/acme.json
      - ./appdata/traefik/config.yml:/config.yml
      - ./appdata/traefik/traefik.yml:/traefik.yml:ro

  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    networks:
      - cloudflared
    ports:
      - '9091:9091'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/NOTIFIER_SMTP_PASSWORD
    volumes:
      - ./appdata/authelia/config:/config
      - ./appdata/authelia/secrets:/secrets
      - ./appdata/authelia/db:/db

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - cloudflared
    ports:
      - 3000:3000
    volumes:
      - ./appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.thehorde.page
      PUID: 1000
      PGID: 1000

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - cloudflared
    environment:
      DOMAIN: https://pass.thehorde.page
      SIGNUPS_ALLOWED: 'true'
    volumes:
      - ./appdata/vaultwarden:/data

  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    volumes:
      - ./appdata/gotify:/app/data
    networks:
      - cloudflared
    ports:
      - 4624:80