http:
  routers:

    authelia:
      entryPoints:
        - web
      rule: Host(`auth.thehorde.page`)
      service: authelia

    homepage:
      entryPoints:
        - web
      middlewares:
        - force-https-header
        - authelia
      rule: Host(`home.thehorde.page`)
      service: homepage

    nas:
      entryPoints:
        - web
      rule: Host(`nas.thehorde.page`)
      service: nas

    hassio:
      entryPoints:
        - web
      rule: Host(`ha.thehorde.page`)
      service: hassio

  services:

    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091

    homepage:
      loadBalancer:
        servers:
          - url: http://homepage:3000

    hassio:
      loadBalancer:
        servers:
          - url: http://42.42.20.4:8123

  middlewares:
    force-https-header:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.thehorde.page%2F
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    authelia-basic:
      forwardAuth:
        address: http://authelia:9091/api/verify?auth=basic
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
